FROM ubuntu:18.04

RUN apt-get update && apt-get install -y \
  build-essential \
  libsdl2-dev \
  python3 \
  python3-pip \
  python3-dev \
  git \
  valgrind vim \
  && rm -rf /var/lib/apt/lists/*

COPY requirements.txt /
RUN pip3 install --upgrade pip && pip3 install --no-cache-dir -r requirements.txt

ADD . /pyboy
WORKDIR /pyboy

RUN pip3 install .
WORKDIR /
