FROM python:3.7-buster

RUN apt-get update && apt-get install -y \
  build-essential \
  libsdl2-dev \
  && rm -rf /var/lib/apt/lists/*

COPY ./requirements.txt .
RUN pip install -r requirements.txt 

COPY . /pyboy
WORKDIR /pyboy

RUN pip install .
WORKDIR /
