FROM ubuntu:18.04
RUN apt-get update && apt-get install -y software-properties-common && add-apt-repository ppa:pypy/ppa
RUN apt-get update && apt-get install -y \
  build-essential \
  libsdl2-dev \
  pypy3 \
  pypy3-dev \
  && rm -rf /var/lib/apt/lists/*

COPY requirements.txt /
RUN pypy3 -m ensurepip && pypy3 -m pip install --upgrade pip && pypy3 -m pip install --no-cache-dir -r requirements.txt

COPY . /pyboy
WORKDIR /pyboy

RUN pypy3 -m pip install .
WORKDIR /
