FROM python:3.7-alpine

RUN apk add\
  sdl2-dev\
  sdl2\
  build-base\
  zlib-dev\
  jpeg-dev

COPY ./requirements.txt .
RUN pip install -r requirements.txt

COPY . /pyboy
WORKDIR /pyboy

RUN pip install .
WORKDIR /
