FROM python:3-buster

RUN apt-get update && apt-get install -y \
  build-essential \
  libsdl2-dev \
  && rm -rf /var/lib/apt/lists/*

COPY requirements.txt /
RUN pip install --upgrade pip && pip install --no-cache-dir -r requirements.txt

ADD . /pyboy
WORKDIR /pyboy

RUN pip install .
WORKDIR /
