FROM python:3-alpine

RUN apk add \
  build-base \
  jpeg-dev \
  sdl2 \
  sdl2-dev \
  zlib-dev

RUN pip install --upgrade pip && pip install -i https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple pyboy

WORKDIR /
