#
# License: See LICENSE file
# GitHub: https://github.com/Baekalfen/PyBoy
#


(QUIT, PRESSARROWUP, PRESSARROWDOWN, PRESSARROWRIGHT, PRESSARROWLEFT,
 PRESSBUTTONA, PRESSBUTTONB, PRESSBUTTONSELECT, PRESSBUTTONSTART,
 RELEASEARROWUP, RELEASEARROWDOWN, RELEASEARROWRIGHT, RELEASEARROWLEFT,
 RELEASEBUTTONA, RELEASEBUTTONB, RELEASEBUTTONSELECT, RELEASEBUTTONSTART,
 DEBUGTOGGLE, PRESSSPEEDUP, RELEASESPEEDUP, SAVESTATE, LOADSTATE, PASS,
 SCREENRECORDINGTOGGLE) = range(24)
