#
# License: See LICENSE file
# GitHub: https://github.com/Baekalfen/PyBoy
#

"""
These are all the supported events to send to the emulator:

    QUIT
    PRESS_ARROW_UP
    PRESS_ARROW_DOWN
    PRESS_ARROW_RIGHT
    PRESS_ARROW_LEFT
    PRESS_BUTTON_A
    PRESS_BUTTON_B
    PRESS_BUTTON_SELECT
    PRESS_BUTTON_START
    RELEASE_ARROW_UP
    RELEASE_ARROW_DOWN
    RELEASE_ARROW_RIGHT
    RELEASE_ARROW_LEFT
    RELEASE_BUTTON_A
    RELEASE_BUTTON_B
    RELEASE_BUTTON_SELECT
    RELEASE_BUTTON_START
    DEBUG_TOGGLE
    PRESS_SPEED_UP
    RELEASE_SPEED_UP
    SAVE_STATE
    LOAD_STATE
    PASS
    SCREEN_RECORDING_TOGGLE
    PAUSE
    UNPAUSE
    PAUSE_TOGGLE
"""

(QUIT,
 PRESS_ARROW_UP,
 PRESS_ARROW_DOWN,
 PRESS_ARROW_RIGHT,
 PRESS_ARROW_LEFT,
 PRESS_BUTTON_A,
 PRESS_BUTTON_B,
 PRESS_BUTTON_SELECT,
 PRESS_BUTTON_START,
 RELEASE_ARROW_UP,
 RELEASE_ARROW_DOWN,
 RELEASE_ARROW_RIGHT,
 RELEASE_ARROW_LEFT,
 RELEASE_BUTTON_A,
 RELEASE_BUTTON_B,
 RELEASE_BUTTON_SELECT,
 RELEASE_BUTTON_START,
 DEBUG_TOGGLE,
 PRESS_SPEED_UP,
 RELEASE_SPEED_UP,
 SAVE_STATE,
 LOAD_STATE,
 PASS,
 SCREEN_RECORDING_TOGGLE,
 PAUSE,
 UNPAUSE,
 PAUSE_TOGGLE,) = range(27)
