# -*- encoding: utf-8 -*-
#
# Authors: Asger Anders Lund Hansen", Mads Ynddal and Troels Ynddal
# License: See LICENSE file
# GitHub: https://github.com/Baekalfen/PyBoy
#

# CPU_COMMANDS = ["CPU_NOP", "CPU_LD", "CPU_LD", "CPU_INC", "CPU_INC", "CPU_DEC", "CPU_LD", "CPU_RLC", "CPU_LD", "CPU_ADD", "CPU_LD", "CPU_DEC", "CPU_INC", "CPU_DEC", "CPU_LD", "CPU_RRC", "CPU_STOP", "CPU_LD", "CPU_LD", "CPU_INC", "CPU_INC", "CPU_DEC", "CPU_LD", "CPU_RL", "CPU_JR", "CPU_ADD", "CPU_LD", "CPU_DEC", "CPU_INC", "CPU_DEC", "CPU_LD", "CPU_RR", "CPU_JR", "CPU_LD", "CPU_LDI", "CPU_INC", "CPU_INC", "CPU_DEC", "CPU_LD", "CPU_DAA", "CPU_JR", "CPU_ADD", "CPU_LDI", "CPU_DEC", "CPU_INC", "CPU_DEC", "CPU_LD", "CPU_CPL", "CPU_JR", "CPU_LD", "CPU_LDD", "CPU_INC", "CPU_INC", "CPU_DEC", "CPU_LD", "CPU_SCF", "CPU_JR", "CPU_ADD", "CPU_LDD", "CPU_DEC", "CPU_INC", "CPU_DEC", "CPU_LD", "CPU_CCF", "CPU_LD", "CPU_LD", "CPU_LD", "CPU_LD", "CPU_LD", "CPU_LD", "CPU_LD", "CPU_LD", "CPU_LD", "CPU_LD", "CPU_LD", "CPU_LD", "CPU_LD", "CPU_LD", "CPU_LD", "CPU_LD", "CPU_LD", "CPU_LD", "CPU_LD", "CPU_LD", "CPU_LD", "CPU_LD", "CPU_LD", "CPU_LD", "CPU_LD", "CPU_LD", "CPU_LD", "CPU_LD", "CPU_LD", "CPU_LD", "CPU_LD", "CPU_LD", "CPU_LD", "CPU_LD", "CPU_LD", "CPU_LD", "CPU_LD", "CPU_LD", "CPU_LD", "CPU_LD", "CPU_LD", "CPU_LD", "CPU_LD", "CPU_LD", "CPU_LD", "CPU_LD", "CPU_LD", "CPU_LD", "CPU_LD", "CPU_LD", "CPU_LD", "CPU_LD", "CPU_LD", "CPU_LD", "CPU_HALT", "CPU_LD", "CPU_LD", "CPU_LD", "CPU_LD", "CPU_LD", "CPU_LD", "CPU_LD", "CPU_LD", "CPU_LD", "CPU_ADD", "CPU_ADD", "CPU_ADD", "CPU_ADD", "CPU_ADD", "CPU_ADD", "CPU_ADD", "CPU_ADD", "CPU_ADC", "CPU_ADC", "CPU_ADC", "CPU_ADC", "CPU_ADC", "CPU_ADC", "CPU_ADC", "CPU_ADC", "CPU_SUB", "CPU_SUB", "CPU_SUB", "CPU_SUB", "CPU_SUB", "CPU_SUB", "CPU_SUB", "CPU_SUB", "CPU_SBC", "CPU_SBC", "CPU_SBC", "CPU_SBC", "CPU_SBC", "CPU_SBC", "CPU_SBC", "CPU_SBC", "CPU_AND", "CPU_AND", "CPU_AND", "CPU_AND", "CPU_AND", "CPU_AND", "CPU_AND", "CPU_AND", "CPU_XOR", "CPU_XOR", "CPU_XOR", "CPU_XOR", "CPU_XOR", "CPU_XOR", "CPU_XOR", "CPU_XOR", "CPU_OR", "CPU_OR", "CPU_OR", "CPU_OR", "CPU_OR", "CPU_OR", "CPU_OR", "CPU_OR", "CPU_CP", "CPU_CP", "CPU_CP", "CPU_CP", "CPU_CP", "CPU_CP", "CPU_CP", "CPU_CP", "CPU_RET", "CPU_POP", "CPU_JP", "CPU_JP", "CPU_CALL", "CPU_PUSH", "CPU_ADD", "CPU_RST", "CPU_RET", "CPU_RET", "CPU_JP", "CPU_Ext", "CPU_CALL", "CPU_CALL", "CPU_ADC", "CPU_RST", "CPU_RET", "CPU_POP", "CPU_JP", "CPU_XX", "CPU_CALL", "CPU_PUSH", "CPU_SUB", "CPU_RST", "CPU_RET", "CPU_RETI", "CPU_JP", "CPU_XX", "CPU_CALL", "CPU_XX", "CPU_SBC", "CPU_RST", "CPU_LDH", "CPU_POP", "CPU_LDH", "CPU_XX", "CPU_XX", "CPU_PUSH", "CPU_AND", "CPU_RST", "CPU_ADD", "CPU_JP", "CPU_LD", "CPU_XX", "CPU_XX", "CPU_XX", "CPU_XOR", "CPU_RST", "CPU_LDH", "CPU_POP", "CPU_XX", "CPU_DI", "CPU_XX", "CPU_PUSH", "CPU_OR", "CPU_RST", "CPU_LDHL", "CPU_LD", "CPU_LD", "CPU_EI", "CPU_XX", "CPU_XX", "CPU_CP", "CPU_RST"]

CPU_COMMANDS = [
    "NOP",
    "LD BC,nn",
    "LD (BC),A",
    "INC BC",
    "INC B",
    "DEC B",
    "LD B,n",
    "RLC A",
    "LD (nn),SP",
    "ADD HL,BC",
    "LD A,(BC)",
    "DEC BC",
    "INC C",
    "DEC C",
    "LD C,n",
    "RRC A",
    "STOP",
    "LD DE,nn",
    "LD (DE),A",
    "INC DE",
    "INC D",
    "DEC D",
    "LD D,n",
    "RL A",
    "JR n",
    "ADD HL,DE",
    "LD A,(DE)",
    "DEC DE",
    "INC E",
    "DEC E",
    "LD E,n",
    "RR A",
    "JR NZ,n",
    "LD HL,nn",
    "LDI (HL),A",
    "INC HL",
    "INC H",
    "DEC H",
    "LD H,n",
    "DAA",
    "JR Z,n",
    "ADD HL,HL",
    "LDI A,(HL)",
    "DEC HL",
    "INC L",
    "DEC L",
    "LD L,n",
    "CPL",
    "JR NC,n",
    "LD SP,nn",
    "LDD (HL),A",
    "INC SP",
    "INC (HL)",
    "DEC (HL)",
    "LD (HL),n",
    "SCF",
    "JR C,n",
    "ADD HL,SP",
    "LDD A,(HL)",
    "DEC SP",
    "INC A",
    "DEC A",
    "LD A,n",
    "CCF",
    "LD B,B",
    "LD B,C",
    "LD B,D",
    "LD B,E",
    "LD B,H",
    "LD B,L",
    "LD B,(HL)",
    "LD B,A",
    "LD C,B",
    "LD C,C",
    "LD C,D",
    "LD C,E",
    "LD C,H",
    "LD C,L",
    "LD C,(HL)",
    "LD C,A",
    "LD D,B",
    "LD D,C",
    "LD D,D",
    "LD D,E",
    "LD D,H",
    "LD D,L",
    "LD D,(HL)",
    "LD D,A",
    "LD E,B",
    "LD E,C",
    "LD E,D",
    "LD E,E",
    "LD E,H",
    "LD E,L",
    "LD E,(HL)",
    "LD E,A",
    "LD H,B",
    "LD H,C",
    "LD H,D",
    "LD H,E",
    "LD H,H",
    "LD H,L",
    "LD H,(HL)",
    "LD H,A",
    "LD L,B",
    "LD L,C",
    "LD L,D",
    "LD L,E",
    "LD L,H",
    "LD L,L",
    "LD L,(HL)",
    "LD L,A",
    "LD (HL),B",
    "LD (HL),C",
    "LD (HL),D",
    "LD (HL),E",
    "LD (HL),H",
    "LD (HL),L",
    "HALT",
    "LD (HL),A",
    "LD A,B",
    "LD A,C",
    "LD A,D",
    "LD A,E",
    "LD A,H",
    "LD A,L",
    "LD A,(HL)",
    "LD A,A",
    "ADD A,B",
    "ADD A,C",
    "ADD A,D",
    "ADD A,E",
    "ADD A,H",
    "ADD A,L",
    "ADD A,(HL)",
    "ADD A,A",
    "ADC A,B",
    "ADC A,C",
    "ADC A,D",
    "ADC A,E",
    "ADC A,H",
    "ADC A,L",
    "ADC A,(HL)",
    "ADC A,A",
    "SUB A,B",
    "SUB A,C",
    "SUB A,D",
    "SUB A,E",
    "SUB A,H",
    "SUB A,L",
    "SUB A,(HL)",
    "SUB A,A",
    "SBC A,B",
    "SBC A,C",
    "SBC A,D",
    "SBC A,E",
    "SBC A,H",
    "SBC A,L",
    "SBC A,(HL)",
    "SBC A,A",
    "AND B",
    "AND C",
    "AND D",
    "AND E",
    "AND H",
    "AND L",
    "AND (HL)",
    "AND A",
    "XOR B",
    "XOR C",
    "XOR D",
    "XOR E",
    "XOR H",
    "XOR L",
    "XOR (HL)",
    "XOR A",
    "OR B",
    "OR C",
    "OR D",
    "OR E",
    "OR H",
    "OR L",
    "OR (HL)",
    "OR A",
    "CP B",
    "CP C",
    "CP D",
    "CP E",
    "CP H",
    "CP L",
    "CP (HL)",
    "CP A",
    "RET NZ",
    "POP BC",
    "JP NZ,nn",
    "JP nn",
    "CALL NZ,nn",
    "PUSH BC",
    "ADD A,n",
    "RST 0",
    "RET Z",
    "RET",
    "JP Z,nn",
    "Ext ops",
    "CALL Z,nn",
    "CALL nn",
    "ADC A,n",
    "RST 8",
    "RET NC",
    "POP DE",
    "JP NC,nn",
    "XX",
    "CALL NC,nn",
    "PUSH DE",
    "SUB A,n",
    "RST 10",
    "RET C",
    "RETI",
    "JP C,nn",
    "XX",
    "CALL C,nn",
    "XX",
    "SBC A,n",
    "RST 18",
    "LDH (n),A",
    "POP HL",
    "LDH (C),A",
    "XX",
    "XX",
    "PUSH HL",
    "AND n",
    "RST 20",
    "ADD SP,d",
    "JP (HL)",
    "LD (nn),A",
    "XX",
    "XX",
    "XX",
    "XOR n",
    "RST 28",
    "LDH A,(n)",
    "POP AF",
    "XX",
    "DI",
    "XX",
    "PUSH AF",
    "OR n",
    "RST 30",
    "LDHL SP,d",
    "LD SP,HL",
    "LD A,(nn)",
    "EI",
    "XX",
    "XX",
    "CP n",
    "RST 38"]



CPU_COMMANDS_EXT = [
    "CPU_EXT_RLC",
    "CPU_EXT_RLC",
    "CPU_EXT_RLC",
    "CPU_EXT_RLC",
    "CPU_EXT_RLC",
    "CPU_EXT_RLC",
    "CPU_EXT_RLC",
    "CPU_EXT_RLC",
    "CPU_EXT_RRC",
    "CPU_EXT_RRC",
    "CPU_EXT_RRC",
    "CPU_EXT_RRC",
    "CPU_EXT_RRC",
    "CPU_EXT_RRC",
    "CPU_EXT_RRC",
    "CPU_EXT_RRC",
    "CPU_EXT_RL",
    "CPU_EXT_RL",
    "CPU_EXT_RL",
    "CPU_EXT_RL",
    "CPU_EXT_RL",
    "CPU_EXT_RL",
    "CPU_EXT_RL",
    "CPU_EXT_RL",
    "CPU_EXT_RR",
    "CPU_EXT_RR",
    "CPU_EXT_RR",
    "CPU_EXT_RR",
    "CPU_EXT_RR",
    "CPU_EXT_RR",
    "CPU_EXT_RR",
    "CPU_EXT_RR",
    "CPU_EXT_SLA",
    "CPU_EXT_SLA",
    "CPU_EXT_SLA",
    "CPU_EXT_SLA",
    "CPU_EXT_SLA",
    "CPU_EXT_SLA",
    "CPU_EXT_SLA",
    "CPU_EXT_SLA",
    "CPU_EXT_SRA",
    "CPU_EXT_SRA",
    "CPU_EXT_SRA",
    "CPU_EXT_SRA",
    "CPU_EXT_SRA",
    "CPU_EXT_SRA",
    "CPU_EXT_SRA",
    "CPU_EXT_SRA",
    "CPU_EXT_SWAP",
    "CPU_EXT_SWAP",
    "CPU_EXT_SWAP",
    "CPU_EXT_SWAP",
    "CPU_EXT_SWAP",
    "CPU_EXT_SWAP",
    "CPU_EXT_SWAP",
    "CPU_EXT_SWAP",
    "CPU_EXT_SRL",
    "CPU_EXT_SRL",
    "CPU_EXT_SRL",
    "CPU_EXT_SRL",
    "CPU_EXT_SRL",
    "CPU_EXT_SRL",
    "CPU_EXT_SRL",
    "CPU_EXT_SRL",
    "CPU_EXT_BIT",
    "CPU_EXT_BIT",
    "CPU_EXT_BIT",
    "CPU_EXT_BIT",
    "CPU_EXT_BIT",
    "CPU_EXT_BIT",
    "CPU_EXT_BIT",
    "CPU_EXT_BIT",
    "CPU_EXT_BIT",
    "CPU_EXT_BIT",
    "CPU_EXT_BIT",
    "CPU_EXT_BIT",
    "CPU_EXT_BIT",
    "CPU_EXT_BIT",
    "CPU_EXT_BIT",
    "CPU_EXT_BIT",
    "CPU_EXT_BIT",
    "CPU_EXT_BIT",
    "CPU_EXT_BIT",
    "CPU_EXT_BIT",
    "CPU_EXT_BIT",
    "CPU_EXT_BIT",
    "CPU_EXT_BIT",
    "CPU_EXT_BIT",
    "CPU_EXT_BIT",
    "CPU_EXT_BIT",
    "CPU_EXT_BIT",
    "CPU_EXT_BIT",
    "CPU_EXT_BIT",
    "CPU_EXT_BIT",
    "CPU_EXT_BIT",
    "CPU_EXT_BIT",
    "CPU_EXT_BIT",
    "CPU_EXT_BIT",
    "CPU_EXT_BIT",
    "CPU_EXT_BIT",
    "CPU_EXT_BIT",
    "CPU_EXT_BIT",
    "CPU_EXT_BIT",
    "CPU_EXT_BIT",
    "CPU_EXT_BIT",
    "CPU_EXT_BIT",
    "CPU_EXT_BIT",
    "CPU_EXT_BIT",
    "CPU_EXT_BIT",
    "CPU_EXT_BIT",
    "CPU_EXT_BIT",
    "CPU_EXT_BIT",
    "CPU_EXT_BIT",
    "CPU_EXT_BIT",
    "CPU_EXT_BIT",
    "CPU_EXT_BIT",
    "CPU_EXT_BIT",
    "CPU_EXT_BIT",
    "CPU_EXT_BIT",
    "CPU_EXT_BIT",
    "CPU_EXT_BIT",
    "CPU_EXT_BIT",
    "CPU_EXT_BIT",
    "CPU_EXT_BIT",
    "CPU_EXT_BIT",
    "CPU_EXT_BIT",
    "CPU_EXT_BIT",
    "CPU_EXT_BIT",
    "CPU_EXT_RES",
    "CPU_EXT_RES",
    "CPU_EXT_RES",
    "CPU_EXT_RES",
    "CPU_EXT_RES",
    "CPU_EXT_RES",
    "CPU_EXT_RES",
    "CPU_EXT_RES",
    "CPU_EXT_RES",
    "CPU_EXT_RES",
    "CPU_EXT_RES",
    "CPU_EXT_RES",
    "CPU_EXT_RES",
    "CPU_EXT_RES",
    "CPU_EXT_RES",
    "CPU_EXT_RES",
    "CPU_EXT_RES",
    "CPU_EXT_RES",
    "CPU_EXT_RES",
    "CPU_EXT_RES",
    "CPU_EXT_RES",
    "CPU_EXT_RES",
    "CPU_EXT_RES",
    "CPU_EXT_RES",
    "CPU_EXT_RES",
    "CPU_EXT_RES",
    "CPU_EXT_RES",
    "CPU_EXT_RES",
    "CPU_EXT_RES",
    "CPU_EXT_RES",
    "CPU_EXT_RES",
    "CPU_EXT_RES",
    "CPU_EXT_RES",
    "CPU_EXT_RES",
    "CPU_EXT_RES",
    "CPU_EXT_RES",
    "CPU_EXT_RES",
    "CPU_EXT_RES",
    "CPU_EXT_RES",
    "CPU_EXT_RES",
    "CPU_EXT_RES",
    "CPU_EXT_RES",
    "CPU_EXT_RES",
    "CPU_EXT_RES",
    "CPU_EXT_RES",
    "CPU_EXT_RES",
    "CPU_EXT_RES",
    "CPU_EXT_RES",
    "CPU_EXT_RES",
    "CPU_EXT_RES",
    "CPU_EXT_RES",
    "CPU_EXT_RES",
    "CPU_EXT_RES",
    "CPU_EXT_RES",
    "CPU_EXT_RES",
    "CPU_EXT_RES",
    "CPU_EXT_RES",
    "CPU_EXT_RES",
    "CPU_EXT_RES",
    "CPU_EXT_RES",
    "CPU_EXT_RES",
    "CPU_EXT_RES",
    "CPU_EXT_RES",
    "CPU_EXT_RES",
    "CPU_EXT_SET",
    "CPU_EXT_SET",
    "CPU_EXT_SET",
    "CPU_EXT_SET",
    "CPU_EXT_SET",
    "CPU_EXT_SET",
    "CPU_EXT_SET",
    "CPU_EXT_SET",
    "CPU_EXT_SET",
    "CPU_EXT_SET",
    "CPU_EXT_SET",
    "CPU_EXT_SET",
    "CPU_EXT_SET",
    "CPU_EXT_SET",
    "CPU_EXT_SET",
    "CPU_EXT_SET",
    "CPU_EXT_SET",
    "CPU_EXT_SET",
    "CPU_EXT_SET",
    "CPU_EXT_SET",
    "CPU_EXT_SET",
    "CPU_EXT_SET",
    "CPU_EXT_SET",
    "CPU_EXT_SET",
    "CPU_EXT_SET",
    "CPU_EXT_SET",
    "CPU_EXT_SET",
    "CPU_EXT_SET",
    "CPU_EXT_SET",
    "CPU_EXT_SET",
    "CPU_EXT_SET",
    "CPU_EXT_SET",
    "CPU_EXT_SET",
    "CPU_EXT_SET",
    "CPU_EXT_SET",
    "CPU_EXT_SET",
    "CPU_EXT_SET",
    "CPU_EXT_SET",
    "CPU_EXT_SET",
    "CPU_EXT_SET",
    "CPU_EXT_SET",
    "CPU_EXT_SET",
    "CPU_EXT_SET",
    "CPU_EXT_SET",
    "CPU_EXT_SET",
    "CPU_EXT_SET",
    "CPU_EXT_SET",
    "CPU_EXT_SET",
    "CPU_EXT_SET",
    "CPU_EXT_SET",
    "CPU_EXT_SET",
    "CPU_EXT_SET",
    "CPU_EXT_SET",
    "CPU_EXT_SET",
    "CPU_EXT_SET",
    "CPU_EXT_SET",
    "CPU_EXT_SET",
    "CPU_EXT_SET",
    "CPU_EXT_SET",
    "CPU_EXT_SET",
    "CPU_EXT_SET",
    "CPU_EXT_SET",
    "CPU_EXT_SET",
    "CPU_EXT_SET"
]



