name: Documentation

on:
  push:
    branches:
      - master
  pull_request:
  release:
    types:
      - released
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --prefer-binary -r requirements.txt
          python -m pip install --prefer-binary -r requirements_tests.txt
          python -m pip install --prefer-binary ".[docs]"
      - name: Generate documentation images
        env:
          PYTEST_SECRETS_KEY: ${{ secrets.PYTEST_SECRETS_KEY }}
        run: make docs-images
      - name: Build documentation
        run: make docs
      - uses: actions/upload-pages-artifact@v3
        if: ${{ github.event_name == 'release' }}
        with:
          path: docs/_build/html

  deploy:
    if: ${{ github.event_name == 'release' }}
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
